### ISSUE TITLE
upload error : java.lang.NullPointerException

### ISSUE THREAD

**Issue by trinhvanhuy** [xfally/cordova-plugin-ftp#1]
Hello everyone
I have a error when i try to upload file using cordova-plugin-ftp
here is my code 

$window.resolveLocalFileSystemURL(cordova.file.externalRootDirectory + path, function(fileSystem) {
                var directoryReader = fileSystem.createReader();
                directoryReader.readEntries(function(entries) {
                    angular.forEach(entries, function(entry) {
                        uploadFileToFTP($rootScope.config.repertoireFichersRCV,   entry.fullPath);
                    });
                    console.log(entries);
                }, function(error) {

```
                $ionicLoading.hide();
                console.log(error);
            });
        }, function(error) {

            $ionicLoading.hide();
            console.log(error);
        });
```

then : 

var uploadFileToFTP = function(subDic, filePath) {
        $ionicLoading.show();
        filePath = filePath.replace('file://', '');
        console.log(filePath);
        $window.cordova.plugin.ftp.upload('/' + subDic + '/' + filePath.replace(/^.*[\\/]/, ''), filePath, function(percent) {
            if (percent == 1) {
                console.log("xtest: ftp: upload finish");
                $ionicLoading.hide();
            } else {
                console.log("xtest: ftp: upload percent=" + percent \* 100 + "%");
            }
        }, function(error) {
            $ionicLoading.hide();
            console.log("xtest: ftp: upload error=" + error);
        });
    };

the error say : 
java.lang.NullPointerException

Thanks

**Comment by xfally** [comment]
Hallo @trinhvanhuy

Did You mean `ftp.upload` throws error `java.lang.NullPointerException`?

Cound you give the detail of `ftp.upload('/' + subDic + '/' + filePath.replace(/^.*[\\/]/, ''), filePath`?

As demo (in README.md) or [ftp.js](https://github.com/xfally/cordova-plugin-ftp/blob/master/www/ftp.js) said, this API will upload `localFile` to `remoteFile`. So the values of them are wanted, and then i can reproduce the error more easily.

**Comment by trinhvanhuy** [comment]
@xfally thanks for reply, here they are : 
filePath   =====>  /storage/emulated/0/AuditPrix_Output/AUD0210211042016
1465218967128.txt
'/' + subDic + '/' + filePath.replace(/^.*[\/]/, '') =======> /www/app_api/data/AUD0210211042016
1465218967128.txt

**Comment by xfally** [comment]
@trinhvanhuy Sorry, i have tried a simple _txt_ file, but can't reproduce the error. It seems `java.lang.NullPointerException` is thrown from lib _ftp4j.jar_. As you see it's a common error, and i can do nothing if can't reproduce it. Could you give some console log (including both web and native log)?

I also noticed that you used `createReader` to traversal a dir. But in `ftp.upload`, you tried to override all files in that dir. I'm confused what do you want to do? In other words, `/storage/emulated/0` and `/www/app_api/data/`, which is your _remote dir_?

**Comment by trinhvanhuy** [comment]
Thanks @xfally 
/www/app_api/data/  is my remote dir
/storage/emulated/0 is my local dir in Android

All i want to do is upload all files txt from folder '/storage/emulated/0' to remote folder /www/app_api/data/  which is in a shared host

**Comment by xfally** [comment]
@trinhvanhuy Please notice that `ftp.upload`'s first arg is `localFile`, and second arg is `remoteFile`. But in your codes, `/www/app_api/data/` was used as local dir, and `/storage/emulated/0` as remote dir. I think you misused this API.

Another little mistake, usually you should use `error.code` in fail callback of cordova-plugin-file.
Refer to http://docs.phonegap.com/en/1.3.0/phonegap_file_file.md.html#FileError

**Comment by trinhvanhuy** [comment]
Im really sorry @xfally 
I forgot to connecting to host before uploading :'( :'( 
Thanks so much, your plugin is very helpful and sorry again for your time
i will close this issue

**Comment by trinhvanhuy** [comment]
Hello @xfally 
I have another questions, for uploading multi files, what is the best way ?

**Comment by xfally** [comment]
@trinhvanhuy Sorry, no good methods currently.

Ftp protocol [rfc959](http://www.w3.org/Protocols/rfc959/) has no advice for this scene, even some ftp tool has implement it, e.g. ftp cmd `mput` on some OS. e.g Linux Ubuntu.

The plugin is created to upload file on both iOS and Android. iOS native codes are based on GoldRaccoon which supports task queue (You can do multi-`addRequestForUploadFileAtLocalPath:toRemotePath` and one-`startProcessingRequests`, but it still uploads files one by one. This is what you want?), and Android native are based on ftp4j which does not support. For API unification, i won't add task queue currently, but maybe in the future. You can also create one PR to implement the feature.

**Comment by trinhvanhuy** [comment]
hello @xfally , i need to upload all file from a folder Android, one by one is ok
I did fetch all file in that folder, then using angular.foreach then call the upload function, but they alway say 'broken bipe' :(

**Comment by trinhvanhuy** [comment]
Hello @xfally  : another thing, if i upload to a server with username and password, it works, but it dont work when i upload to a ftp server anonymous :(  

the error message is : 
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)

**Comment by xfally** [comment]
For 1st question, ftp plugin just init one connection and upload all files via that connection. As `foreach` is asychronous, so you start multi-uploads in a short time, which will mess the transfer. You can try to use [async](https://github.com/caolan/async) to upload one after one.

For 2nd question, anonymous is supported. Could you give the connect args?

**Comment by trinhvanhuy** [comment]
hello @xfally here is my code for uploading to anonymous
`$window.resolveLocalFileSystemURL(cordova.file.externalRootDirectory + path, function (fileSystem) {
                var directoryReader = fileSystem.createReader();
                directoryReader.readEntries(function (entries) {
                        if (entries.length > 0) {

```
                        $window.cordova.plugin.ftp.connect($rootScope.config.serveurFTP, $rootScope.config.utilisateurFTP, $rootScope.config.motDePasseFTP,
                            function () {

                                var i = 0;
                                var uploadfunc = function (index) {
                                    console.log(index);
                                    console.log(entries[index].nativeURL);
                                    uploadFileToFTP(decodeURIComponent(entries[index].nativeURL), $rootScope.config.repertoireFichersSND).finally(function () {
                                        i++;
                                        if (i < entries.length) {
                                            uploadfunc(i);
                                        } else {
                                            $ionicLoading.hide();
                                        }
                                    })
                                };
                                uploadfunc(i);
                            },
                            function (error) {
                                $ionicLoading.hide();
                                console.log(error);

                            });
                    }
                    console.log(entries);
                },
                function (error) {

                    $ionicLoading.hide();
                    console.log(error);
                });
        });`
```

**Comment by trinhvanhuy** [comment]
and here is the function for uploading 

`var uploadFileToFTP = function (filePath, subDic) {
        var deferred = $q.defer();
        $ionicLoading.show();
        filePath = filePath.replace('file://', '');
        var fileName = filePath.replace(/^.*[\\/]/, '');
        var subTarget = subDic + '/' + fileName;

```
    console.log(filePath);
    console.log(subTarget);

    // $window.cordova.plugin.ftp.connect($rootScope.config.serveurFTP, $rootScope.config.utilisateurFTP, $rootScope.config.motDePasseFTP, function() {
    $window.cordova.plugin.ftp.upload(filePath, subTarget, function (percent) {
        if (percent == 1) {
            $ionicLoading.hide();
            console.log("xtest: ftp: upload finish");
            $ionicPopup.alert({
                title: 'Succès',
                template: 'Le fichier : ' + fileName + ' est bien uploadé'
            });
            $cordovaFile.removeFile('file://' + filePath.replace(fileName, ''), filePath.replace(/^.*[\\\/]/, ''))
                .then(function (success) {
                    $ionicLoading.hide();
                    console.log("File removed!");
                    deferred.resolve('success');
                }, function (error) {
                    $ionicLoading.hide();
                    console.log("error deleting the file " + error.code);
                    deferred.resolve('success');
                });
        } else {
            console.log("xtest: ftp: upload percent=" + percent * 100 + "%");
        }
    }, function (error) {
        deferred.reject(error);
        $ionicLoading.hide();
        console.log(error);
    });
    // }, function(error) {
    //     $ionicLoading.hide();
    //     console.log(error);
    // });
    return deferred.promise;
};`
```

**Comment by trinhvanhuy** [comment]
params : 

'serveurFTP' : '10.13.4.253',
        'portFTP' : '',
        'utilisateurFTP' : 'anonymous',
        'motDePasseFTP' : 'anonymous@',  // i already tried with '' too

**Comment by xfally** [comment]
Your codes seem ok, and it may be the server's fault. What ftp server do you use? Did you test it's anonymous login with other ftp client?

Tip: please paste your codes in two ``` which make reading easier.

**Comment by trinhvanhuy** [comment]
thanks Pax, i will verify immediate

**Comment by trinhvanhuy** [comment]
hello @xfally , i verified the server with fileizila, and i've verified write permission too, they are all ok :( I've tried with another server too, but it seems to work with an shared host online, not with ftp server local :/ 
Do you have any suggession ?
thanks in advance

**Comment by xfally** [comment]
Yet you did not tell me what ftp server used? Anonymous authentication, if admitted by the connected service, can be done sending the username "anonymous" and an arbitrary password (note that some servers require an e-mail address in place of the password).

And what did you mean "work with an shared host online, not with ftp server local"?

**Comment by trinhvanhuy** [comment]
@xfally  thanks for reply, the server ftp is at the office of my client, 
Work with shared host online , mean i rent a ftp server from OVH.com, they gave me ID, password and your plugin work with that server ftp
I will try to test more and try to resolve problem now ( cause the problem might be from server ) then i will tell you later
Thanks so much

**Comment by trinhvanhuy** [comment]
here is the log that i have
![screen shot 2016-08-01 at 09 31 30](https://cloud.githubusercontent.com/assets/1912664/17286578/d3e4a5ec-57ca-11e6-97c7-137b077d06cd.png)

**Comment by xfally** [comment]
I have no idea. But as i suggested before, you can setup one local ftp server (e.g. vsftpd has been tested by me and works well). If anonymous login passed, we can say the issue is fault of your client's ftp server, then you should request more info from your client. Good luck!

**Comment by trinhvanhuy** [comment]
thanks Pax
