### ISSUE TITLE
Error in Error callbackId: Ftp528351193 : TypeError: Cannot read property 'isStopped' of null

### ISSUE THREAD

**Issue by olaferlandsen** [xfally/cordova-plugin-ftp#11]
Error in Error callbackId: Ftp528351193 : TypeError: Cannot read property 'isStopped' of null

**Comment by xfally** [comment]
Could you afford more info about your test? e.g. cordova version, android device model and more... It would be better if you can afford sample codes which can reproduce the error, thanks.

**Comment by xfally** [comment]
Well, the error has gone away?

**Comment by olaferlandsen** [comment]
This error is not part of this plugin, sorry

**Comment by rmzamo1993** [comment]
Same error, what was the error, how did you fix it?
