### ISSUE TITLE
how i can close connection???

### ISSUE THREAD

**Issue by olaferlandsen** [xfally/cordova-plugin-ftp#12]
well, i have connect, cancel, but not close or exit.

**Comment by xfally** [comment]
Sorry, the plugin currently has no methods to close connection explicitly, but can add it latter. So when will the connection be closed? For iOS, when task (list, upload, download...) finished or `cancel` asked, the connection will be closed automatically. For Android, just be closed when ftp connection timeout, which is surely a bug, as reminded in [README.md](https://github.com/xfally/cordova-plugin-ftp) TODO section. I will fix it (providing the `close` action) in the near future.
