### ISSUE TITLE
Add option to change default port connection

### ISSUE THREAD

**Issue by krlozadan** [xfally/cordova-plugin-ftp#15]
Hello!
First of all I'd like to thank you developing this plugin. I have a little suggestion to improve it.

It would be great if there was a way to **change the port** when making a connection to the service. I think that could make the plugin even more useful.

Thanks and I hope you take this improvement into consideration.

Best, Adan

**Comment by xfally** [comment]
Good idea.

I have uploaded one [commit](https://github.com/xfally/cordova-plugin-ftp/commit/654e3864adabf5e0dde00b1c26bf74c169e609e4) on **develop** branch to support the feature. I have also tested it on Android device and work well, but no Apple device to test now. Could you help to cherry-pick and test it (in especial on one Apple device)?

As you can see, i did not modify any ios codes, and i think the current codes will work well with ftp address  with port (e.g. `192.168.1.1:21`). If not, tell me, thanks.

**Comment by krlozadan** [comment]
Great!! I will test it and let you know the outcome. So what you're telling me is that it will just simply work if you place the host name like this: `231.234.1.100:2100`? I suppose it will also work if you use `yourdomain.com:2100`

Also I will open another issue regarding connection timeout

**Comment by xfally** [comment]
Yes, domain name is supported as said in README.md or ftp.js.

**Comment by krlozadan** [comment]
Hi! I'm getting "Unknown Host Exception: Host is unresolved" every time I type the port. 
If I don't type it, it works fine. Any ideas why? I'm using Ionic 3 and ionic-native code and it seems it should work just fine, because there's no argument/data manipulation at all during the process.
I'm using this: 
[https://ionicframework.com/docs/native/ftp/](url)

**Comment by xfally** [comment]
Sorry for no reply too long. I have an new job, and so busy recently. Maybe i can check the error this week, and process the issue before August, haha.

**Comment by xfally** [comment]
@krlozadan Both Android and iOS threw the same error?

**Comment by duplousadecv** [comment]
@xfally Could not check iOS system only Android. do you need any testing from my side or something?

**Comment by xfally** [comment]
@duplousadecv As no apple device on my hand, i will be very grateful if you do me a favour.

One new [commit](https://github.com/xfally/cordova-plugin-ftp/commit/13e09219bb053030dbbee758c40acaa7806e8d03) has been created on **develop** branch, I wrote the codes, but not sure it will work well. Please have a try. You can also find the useful info in these Apple developer docs:

1. https://developer.apple.com/documentation/cfnetwork/1426792-cfreadstreamcreatewithftpurl
2. https://developer.apple.com/documentation/corefoundation/1539615-cfreadstreamsetproperty
3. https://developer.apple.com/documentation/corefoundation/cfstream/stream_properties

**Comment by krlozadan** [comment]
@xfally ok I'll dig into it and let you know. Also, I noticed you made some changes on the master branch. Will that affect the behavior of this one? I mean would that be the reason why this branch isn't working as expected?

**Comment by xfally** [comment]
No influence. It's another feature asked for issue #17. Both master and develop branch have applied it.

Please pull develop branch to test this issue, thanks.

**Comment by krlozadan** [comment]
This seems to be working properly! Thank you very much!

**Comment by krlozadan** [comment]
Could you please merge the branch to the master?? I'm having a lot of trouble using `cordova plugin add https://github.com/xfally/cordova-plugin-ftp#develop` I think it is because of the npm version I'm using but not quite sure. Do you know any other way add a plugin using a specific branch?

**Comment by xfally** [comment]
Merged and v1.1.0 released. See
https://github.com/xfally/cordova-plugin-ftp
https://www.npmjs.com/package/cordova-plugin-ftp
