### ISSUE TITLE
Upload upload - Error: No such file or directory

### ISSUE THREAD

**Issue by Lopuch** [xfally/cordova-plugin-ftp#17]
Hello,
I don't know how to insert corect path to local file.
I am using the android device.

I have created a file:
this.file.writeFile(this.file.dataDirectory + "/mydir/", "image.txt", this.imgSrc, { replace: true })
          .then(_ =>  this.showAlert('writeFile OK', "", "FTS"))
          .catch(err => this.showAlert('writeFile fail', "", err));

The file is created. I can read the content of it.

But when i try to upload the file, it ends up with an error: java.io.FileNotFoundException:file:/data/data/appName/mydir/image.txt: open failed: ENOENT (No such file or directory)

this.ftp.connect('aserver', 'login', 'pass')
      .then(() => {
        this.ftp.upload(this.file.dataDirectory+ "/mydir/image.txt", "/test/ftpimg.txt")
          .then((res: any) => this.showAlert("OK", "FTP", res))
          .catch((error: any) => this.showAlert("FAIL", "FTP", error));
      })
      .catch((error: any) => this.showAlert("FAIL", "connect", error));

Any suggestion?
Thank you :-)

**Comment by xfally** [comment]
Print the path. Remove the protocol prefix "file:" if it exists. Refer to issue#5.

**Comment by flokixdev** [comment]
@xfally Maybe, there could be input check whether the path begin with file:// and if so, remove it automatically. I think that it's a common complication and it has easy solution without BC break. #5

**Comment by Lopuch** [comment]
Thank you!! It solved my problem. The path has to be without "file:"

**Comment by xfally** [comment]
@Lopuch, Good news.

@miloshavlicek, Both README.md and ftp.js have shown the path example without `file:` or `file://` prefix. But as you suggested, it's good to check and remove the prefix automatically. So i will patch the feature soon. Because i don't want to reply the similar issue time time again...

**Comment by xfally** [comment]
Already [committed](https://github.com/xfally/cordova-plugin-ftp/commit/746ad1445b63df217de6fd3042396e1ea4cc4b33).
