### ISSUE TITLE
Upload from iOS does not give proper file size

### ISSUE THREAD

**Issue by nive745** [xfally/cordova-plugin-ftp#18]
Seems there is either some data loss or its not returning correct filesize. The files uploaded to ftp server always have few bytes less than what the plugin returns.

**Comment by xfally** [comment]
So which one is right? Could you try to upload one text or video file, and check its content and size?

Do all files of different type or different size have the issue?

**Comment by nive745** [comment]
We tried uploading video files. The uploaded file size is not correct. The video seems to be trimmed by few seconds at the end. Also, its not consistent. Sometimes, last 3 seconds got trimmed, sometimes last 2 seconds and 1 or 2 times the whole file got uploaded successfully too.
It works fine in Android, but does not in iOS.

**Comment by xfally** [comment]
I want to help you so much, but no apple devices on hand currently. I'm so sorry, but maybe you can (use xcode to) debug it by yourself... It should not be so hard.

As plan, i want to contribute this plugin to the community, or add some collaborators to help maintaining and improving it. If anyone is interested, tell me.

**Comment by xfally** [comment]
Long time no feedback.

**Comment by iadimitriu** [comment]
I found this problem on Android too. When I download multiple files, some of them have missing bits (1 - 5 bits). 
P.S. I download zip files
