### ISSUE TITLE
upload success  but present is less then 1.is 0.0x ; In the local area network 

### ISSUE THREAD

**Issue by zhiyoujingtian** [xfally/cordova-plugin-ftp#19]
This situation in Androids

**Comment by xfally** [comment]
I tested `upload` and `download` on Nexus 5X Android 4.4.2, and it worked well. Could you afford more details or the codes which can reproduce the issue?

**Comment by zhiyoujingtian** [comment]
android 6.2.3;
this.UploadCERT is a obj  ,   contain ftp infomations;
upload code:
  this.ftp.connect(this.UploadCERT.uploadUrl,this.UploadCERT.username, this.UploadCERT.password).then((res: any) => {
          console.log('login successful', res)
          this.ftp.upload(files[0].localURL.replace('cdvfile://localhost/', ''), this.UploadCERT.upLoadFile+ '123456.mp4').then((res: any) => {
            console.log(res)
            // if (res == 1) {
            //   console.info("ftp: upload finish");
            // } else {
            //   console.debug("ftp: upload percent=" + res * 100 + "%");
            // }

          }).catch((Error: any) => { console.log('fail', Error) })
        }).catch((err: any) => { console.log(err) })
..........................
this app run in HUAWEi P9

**Comment by zhiyoujingtian** [comment]
thank you very much

android 6.2.3;
this.UploadCERT is a obj , contain ftp infomations;
upload code:

```
this.ftp.connect(this.UploadCERT.uploadUrl,this.UploadCERT.username, this.UploadCERT.password).then((res: any) => {
    console.log('login successful', res)
    this.ftp.upload(files[0].localURL.replace('cdvfile://localhost/', ''), this.UploadCERT.upLoadFile + '123456.mp4').then((res: any) => {
        console.log(res)
        // if (res == 1) {
        // console.info("ftp: upload finish");
        // } else {
        // console.debug("ftp: upload percent=" + res * 100 + "%");
        // }
    }).catch((Error: any) => { console.log('fail', Error) })
}).catch((err: any) => { console.log(err) })
```

this app run in HUAWEi P9

**Comment by xfally** [comment]
One suggestion, please format your codes when pasted into comment (i have done it for you this time).

I also tested on Nexus 5X Android 6.0.0, and work well (means always reach the percent `1` at last).

I notices the issue title "upload success but present is less then 1.is 0.0x", but i can't get the point. Do you mean the percent always change from `0` to `0.0xxx`, and can't reach `1`? Could you paste the full log? And one more question, your tested file's size is very small?

**Comment by zhiyoujingtian** [comment]
ok,I'll pay attention next time.
I upload a file(5MB ),this is my log 
`login successful Connect and login OK.
 ftp: upload percent=1.3510934%`

**Comment by zhiyoujingtian** [comment]
ok,I'll pay attention next time.
I upload a file(5MB ),this is my full log 
`login successful Connect and login OK`
`ftp: upload percent=1.3510934%`
the percent always change from `0` to `0.0xxx`,cant't reach 1.
the file I test is 5MB to 200MB

**Comment by xfally** [comment]
As i can't reproduce the issue, it's recommended to debug the plugin (js and java) by yourself.

But you can also try my [ftp demo](https://github.com/xfally/x-ionic-seed/blob/feature/demo/ion/www/mod/test/mod.js) on your device, and tell me the result. You can fetch the project and run it with ionic lib v1. See readme for more info.

**Comment by zhiyoujingtian** [comment]
OK,thank you.

**Comment by xfally** [comment]
Long time no feedback.
