### ISSUE TITLE
Code 501 No file name

### ISSUE THREAD

**Issue by nhernandez2** [xfally/cordova-plugin-ftp#20]
Dear,

I'm trying to upload a ZIP from a mobile application. I get the error when I try to publish to my ftp. In yes, for what I understand the error is not on the side of the application since it does not claim that the file does not exist, therefore I understand that FTP can be the error. However when I test the connection on Android I get an OK, then connect I upload but there is where I receive

`ftp: upload error = it.sauronsoftware.ftp4j.FTPException [code = 501, message = No file name]`

**Comment by xfally** [comment]
Which plugin version? Could you show or print the local path of that file, and the code segment you use the plugin API?

**Comment by nhernandez2** [comment]
The version is: `cordova-plugin-ftp 1.1.0 "Ftp"` I am using the following code: 

Value of response1.fileURL = `file:///storage/emulated/0/test/9797241/aksjakskajs-005-00001.pdf `

`window.cordova.plugin.ftp.connect('miftp', 'admin', '12345', function(ok) {`
	`console.info("ftp: connect ok=" + ok);`
	   ` window.cordova.plugin.ftp.upload(response1.fileURL, 'public_html/', function(percent) {`
		 `   if (percent === 1) {`
			     `console.info("ftp: upload finish");`
		    `} else {`
			    `console.debug("ftp: upload percent=" + percent * 100 + "%");`
		   ` }`
	   `}, function(error) {`
		  `console.error("ftp: upload error=" + error);`
	   `});`
` }, function(error) {`
	`console.error("ftp: connect error=" + error);`
`});`

**Comment by xfally** [comment]
Rename `public_html/` to `public_html/aksjakskajs-005-00001.pdf`. As said in ftp.js, fullpath is wanted.

**Comment by nhernandez2** [comment]
Thanks!, that was the problem, I did not know that the file was also re-named.

Regards!
