### ISSUE TITLE
Download progress doesn't finish

### ISSUE THREAD

**Issue by Arsyad** [xfally/cordova-plugin-ftp#21]
I have a file on FTP server which is about 3KB and when I download the file, the progress is sometimes 1, and sometimes is less than 0.50 (e.g. 0.45). However, the file is downloaded. 

Is there something stopping it from firing or is the file size too small? Any other way to check if the file has been downloaded?

I am using version 1.1.0 and with Ionic 3.

**Comment by xfally** [comment]
1. Android or iOS?
2. Bigger file has the same issue?

**Comment by Arsyad** [comment]
1. Android 5.0.2, Samsung Galaxy Tab S
2. Yes same issue too. I tried with a 300+kb PNG as well. 

I also tried with upload and it gave the same issue. File got uploaded.

Somehow the progress isn't firing and no errors.  Wonder if it's my code or anything to do with Ionic? Is there any verbose mode?

Here is my code sample:

```
// This runs ok and shows file exists
testCheckFile() {

      // File is stored inside download folder
      let filedirExt:string = this.file.externalRootDirectory + 'Download/';
      let filename:string = 'test.png';

      this.file.checkFile(filedirExt, filename)

        .then(
          (res) => {

                console.log('File found? ' + res);
                this.testUploadFile();
          })

          .catch(e => {
                console.log('File read error', e)
          });
}

// Res always returns below 1 and progress doesn't fire off after that. No errors fired
testUploadFile() {

      // File is stored inside download folder
      let filedirExt:string = this.file.externalRootDirectory + 'Download/';
      let filename:string = 'test.png';
      let remoteFilePath:string = '/' + filename;
      let localFilePath:string = filedirExt + filename;

      // This gives the path file:///storage/emulated/0/Download/test.png which is valid
      console.log('Uploading file ' + localFilePath);

      this.ftp.connect('host:21', 'username', 'password')
          .then((res: any) => {

                console.log('Login successful', res);

                this.ftp.upload(localFilePath, remoteFilePath)
                  .then((res: any) => {

                      console.log('Upload file progress - ' + res);

                      if (res == 1) {
                          console.log('FTP upload done');
                      }
                  })

                  .catch((error: any) => {
                        console.error('FTP upload error: ' + error)
                  });

            })

          .catch((error: any) => console.error('FTP connect error: ' + error));

  }

// Res always returns below 0.50 and progress doesn't fire off after that. No errors fired
  testDownloadFile() {

      let filename:string = 'test.png';
      // File will be stored inside download folder
      let localFilePathDownload:string = this.file.externalRootDirectory + 'Download/' + filename;

      this.ftp.download(localFilePathDownload, '/' + filename)
          .then((res: any) => {

                console.log('Download file progress - ' + res);

                if (res == 1) {
                    console.log('FTP download done');
                }
          })

          .catch((error: any) => {
                console.error('FTP download error: ' + error);
          });

  }
```

The console in remote debugging returns:

> File found? true
> file:///storage/emulated/0/Download/test.png
> Login successful Connect and login OK.
> Upload file progress - 0.176014

**Comment by xfally** [comment]
The progress just print only once?

**Comment by Arsyad** [comment]
Yes just once

**Comment by xfally** [comment]
Aha, it seems like your **Promise** API `resolve` the progress result, not `notify` to fire the subsequent progress, or maybe the wrong use of it. Every modern browser affords its implemented Promise, and some third-party affords it too. Refer to https://github.com/xfally/cordova-plugin-ftp/blob/master/README.md or https://github.com/xfally/x-ionic-seed/blob/feature/demo/ion/www/mod/test/mod.js for some suggestion or demo.

**Comment by Arsyad** [comment]
Does that mean the issue is with Ionic? It says in the documentation the upload function will return a promise - https://ionicframework.com/docs/native/ftp/

But I am not sure if the promise resolves or notify every time there is a progress.

**Comment by Arsyad** [comment]
It does look like the issue is with Ionic's version. I manage to get it working using the one from this repo - https://github.com/olaferlandsen/cordova-plugin-ftp

It has uploadWithProgress and downloadWithProgress which does the job very well.
