### ISSUE TITLE
Build errors from XCode

### ISSUE THREAD

**Issue by smartyw** [xfally/cordova-plugin-ftp#24]
Hi, I get several build errors from XCode when I build the Cordova ios project:

<img width="248" alt="screen shot 2017-11-17 at 14 22 22" src="https://user-images.githubusercontent.com/1387793/32951753-02e8e798-cba3-11e7-845d-d497c1ebed76.png">

Any ideas?

Thanks!

**Comment by xfally** [comment]
You didn't tell the Xcode version and which line throw error. So i just guess it seems that you use an newer XCode version, and the compiler has changed its default behavior when processing `@synthesize`.

Try
 
```
diff --git a/src/ios/GoldRaccoon/Sources/GRRequestsManager.m b/src/ios/GoldRaccoon/Sources/GRRequestsManager.m
--- a/src/ios/GoldRaccoon/Sources/GRRequestsManager.m
+++ b/src/ios/GoldRaccoon/Sources/GRRequestsManager.m
@@ -19,6 +19,8 @@
 
 @interface GRRequestsManager () <GRRequestDelegate, GRRequestDataSource>
 
+@property (nonatomic, copy) NSString *hostname;
+@property (nonatomic, copy) NSNumber *port;
 @property (nonatomic, copy) NSString *username;
 @property (nonatomic, copy) NSString *password;
 @property (nonatomic, strong) NSMutableData *currentDownloadData;
@@ -37,8 +39,6 @@
 
 @implementation GRRequestsManager
 
-@synthesize hostname = _hostname;
-@synthesize port = _port;
 @synthesize delegate = _delegate;
 
 #pragma mark - Dealloc and Initialization
```

**Comment by smartyw** [comment]
Sorry, I'm running Xcode 8.3.2

Errors are as follows:

GRRequestsManager.m:41:13: Property implementation must have its declaration in interface 'GRRequestsManager' or one of its extensions

GRRequestsManager.m:60:9: Use of undeclared identifier '_port'

GRRequestsManager.m:77:9: Use of undeclared identifier '_port'; did you mean 'port'?

GRRequestsManager.m:266:17: Property 'port' not found on object of type 'GRRequestsManager *'

After your suggested changes I get three compilation errors:

GRRequestsManager.m:22:1: Illegal redeclaration of property in class extension 'GRRequestsManager' (attribute must be 'readwrite', while its primary must be 'readonly')

GRRequestsManager.m:58:9: Use of undeclared identifier '_hostname'; did you mean 'hostname'?

GRRequestsManager.m:75:9: Use of undeclared identifier '_hostname'; did you mean 'hostname'?

**Comment by jondediego** [comment]
We have the same issue here. Running XCode version 9. After trying changes xfally suggested we get the errors:
GRRequestsManager.m:58:9: Use of undeclared identifier '_hostname'; did you mean 'hostname'?

GRRequestsManager.m:75:9: Use of undeclared identifier '_hostname'; did you mean 'hostname'?

**Comment by lugler** [comment]
https://github.com/vlinde/cordova-plugin-ftp

**Comment by xfally** [comment]
@lugler If you fixed the issue, a PR is welcome.

**Comment by jondediego** [comment]
For me @lugler modifications fixed the build errors. Althought I haven’t been able to test yet if ftp worked

**Comment by xfally** [comment]
Fixed in [commit](https://github.com/xfally/cordova-plugin-ftp/commit/80fdcce61ac6232dd03a62da80b4bd102c8dd71f).

**Comment by BhupeshRohilla** [comment]
Hi @xfally ,
Thanks for making this plugin.
In the commit which you mentioned, you disabled the support of port for iOS.
Is it possible to enabling it again by any fixes?
Thanks.
