### ISSUE TITLE
Open FTP URL on device browser

### ISSUE THREAD

**Issue by sumitsoman** [xfally/cordova-plugin-ftp#26]
Can this plugin be used to open a PDF file in the device browser which is available on FTP Server? I have a URL of the format:

`ftp://user:pass@ipaddress/filepath/*.pdf`

Can some sample code be provided too?

**Comment by xfally** [comment]
Open and show pdf directly? Sorry can't. It shoud be the behavior of browser if you use browser or DOM API to open the url. As an alternative, try to download pdf and open it with pdf.js or other plugin. Good luck~
