### ISSUE TITLE
Error uploading sqlite db

### ISSUE THREAD

**Issue by jondediego** [xfally/cordova-plugin-ftp#27]
When I try to upload to a fp server a txt file it works as expected. But if I try to upload sqlite database, the upload is finnished but the file is corrupt because there are left the last bytes of the file.

**Comment by lzynihao** [comment]
@jondediego Have you fixed this issue?

**Comment by xfally** [comment]
ios or android? and the file size?

**Comment by lzynihao** [comment]
ios. I think the size maybe more than 1G even bigger.

**Comment by jondediego** [comment]
I haven't fixed this. My database is about 8MB and I am testing in IOS. I am using ionic native ftp but I have tested using only this cordova plugin and the result is the same. Sometimes the whole file is uploaded, but most of the times last bytes are not uploaded. I think this could be happening in all kind of files but txt files open correctly (only they lose some data in the end), but database cannot be opened if db info is not complete.

**Comment by xfally** [comment]
I will try to reproduct the error this week, but as busy work, a little time is left to maintain this plugin, so the issue will be replied a little later.

**Comment by xfally** [comment]
I have tried to upload sqlite db which is 10MB, from iOS 14.5 to vsftpd, and work well. Please try the latest v1.2.1. If error still exists, reopen this issue.
