### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by cepm-nate** [xfally/cordova-plugin-ftp#28]
I'm trying to connect to a FTP server that has TLS only, but am not sure how to specify it as TLS.

If I say the address is "ftps://myurl:myport", it responds with **Java.net.UnknownHostException.** But if try just the "myurl:myport" by itself, it responds with **[code=550, message= SSL/TLS required on the control channel]**
It looks like it tries to connect without using TLS/SSL, so how do I tell it to try to use TLS/SSL in the connection?

**Comment by xfally** [comment]
Sorry, ftps (over SSL/TLS) is not supported currently. But the feature can be added easily into the plugin for Android platform.

**Comment by cepm-nate** [comment]
Bummer, Thanks for letting me know!

**Comment by xfally** [comment]
I have uploaded one commit to finish the method `setSecurity()` at branch feature/ftps

https://github.com/xfally/cordova-plugin-ftp/tree/feature/ftps

Read the method description in ftp.js, and try it!

**Comment by cepm-nate** [comment]
I'm actually programmin my own node-express server to handle my small use case, but will give your plugin a shot soon!

Sadly I also have to support iOS (custom port number). Does the underlying library you use support a custom port number/range for FTPS on iOS?

**Comment by codecranch** [comment]
Im download code from at branch feature/ftps. Why setSecurity not function? 
ftp.jp include 

`Ftp.prototype.setSecurity`

cordova platform remove android & cordova platform add android fix error

But new error: setSecurity('ftps') ->  Invalid action
Im expected in java code 
`this.client.setSecurity(securityType)`
run before 
`this.client = new FTPClient();`

**Comment by MaxSereda** [comment]
Hi all
I have the same error after call method setSecurity('ftps')

> setSecurity('ftps') -> Invalid action

Can you please advise how to solve this problem?

**Comment by NicolasBuergler** [comment]
Hi

I have also the same error. (Invalid action). Have someone found out how to solve this problem?

**Comment by xfally** [comment]
@NicolasBuergler @MaxSereda @ufocool @cepm-nate  Already fixed. Try the latest v1.2.0. If error still exists, reopen this issue.
