### ISSUE TITLE
Not Logged in Error with correct credentials

### ISSUE THREAD

**Issue by Harrisandwich** [xfally/cordova-plugin-ftp#3]
When I try to connect I always get a "Not Logged In" error. I'm sure my credentials are correct as I can connect via FileZilla just fine. 

Some details:

I'm not using Ionic and this function is not in an angular controller right now.
I'm using it on ios.
The FTP address is not a straight IP. It's an address like "xxx-xxx-xxx.net"

Thank you

My code: 

ftp.connect(FTP.ADDRESS, FTP.USERNAME,FTP.PASS,function() {
            //list driectories
            console.log("connected?"); ftp.ls('/DigiDetailHost/', function(fileList) {
                console.log(fileList); if (fileList && fileList.length > 0) 
                {
                    console.log("xtest: ftp: The last file'name is " + fileList[fileList.length - 1].name);
                    console.log("xtest: ftp: The last file'type is " + fileList[fileList.length - 1].type);
                    console.log("xtest: ftp: The last file'link is " + fileList[fileList.length - 1].link);
                    console.log("xtest: ftp: The last file'size is " + fileList[fileList.length - 1].size);
                    console.log("xtest: ftp: The last file'modifiedDate is " + fileList[fileList.length - 1].modifiedDate);
                }

```
        },function(error){console.log(error);});
    });
```

**Comment by xfally** [comment]
Domain name is supported and has been tested. As README.md Notice said, `ftp.connect` always returns _success_ on iOS, so your error was thrown from `ftp.ls`, right? Could you give the log from native codes (Xcode will show them)?

And what ftp server do you use? online ftp server? Maybe i could reproduce the error.

**Comment by Harrisandwich** [comment]
It's an online Azure site. If it's any help, in order to log in on FileZilla my settings must be "Plain FTP (insecure)" for it to work. Though that doesn't seem like the problem here I thought I might as well tell you everything I can hahaha

I have it throwing the error on the ftp.ls function. Here's the output from Xcode

```
2016-08-11 08:44:50.496 DigiDetail-Player[61000:1562757] requestsManager:didScheduleRequest:
2016-08-11 08:44:50.746 DigiDetail-Player[61000:1562757] requestsManager:didFailRequest:withError: 
 Error Domain=com.albertodebortoli.goldraccoon Code=-1000 "(null)" UserInfo={message=Not logged in.}
```

**Comment by xfally** [comment]
I don't have Azure account, so couldn't test it. If the ftp server on Azure is maintained by you, then you could review the log on server, which may be the fastest and best way to locate the issue. However i could give some suggestions on codes level.

This plugin (iOS version) is implemented based [GoldRaccoon](https://github.com/albertodebortoli/GoldRaccoon), and the later is based on [CFFTP](https://developer.apple.com/library/mac/documentation/Networking/Conceptual/CFNetwork/CFFTPTasks/CFFTPTasks.html#//apple_ref/doc/uid/TP30001132-CH9-DontLinkElementID_1). In file [GRStreamInfo.m](https://github.com/xfally/cordova-plugin-ftp/blob/master/src/ios/GoldRaccoon/Sources/Utils/GRStreamInfo.m), find API `openRead` --> line `[self.readStream open]`. As CFFTP doc said:

`After the correct properties have been assigned to the read stream, open the stream using the CFReadStreamOpen function. Assuming that this does not return an error, all the streams have been properly set up.`

Regretful GoldRaccoon didn't use `CFReadStreamOpen` to open `CFReadStreamRef`, but use `[self.readStream open]` (force casted from `self.readStream = ( __bridge_transfer NSInputStream *) readStreamRef`). As you see, it has the same effect generally, but `- (void)open` has no returned code, so we could not judge the open result intuitively. Although it sets `dispatch_after` to expect `kGRFTPClientStreamTimedOut`, but not helpful here. (This is also why README.md says `ftp.connect` always returns success on iOS). The error "Not logged in" is thrown from `streamEvent` when you do _list_.

Anyway, we could check the `CFReadStreamSetProperty` args e.g. `kCFStreamPropertyFTPUserName`... before. You can try to create some breakpoints in function `openRead` and see whether those args are what you expect? are different from FileZilla? Good luck!

**Comment by xfally** [comment]
Long time no feedback.
