### ISSUE TITLE
java.io.FileNotFOundException 

### ISSUE THREAD

**Issue by simonkincaidkintronix** [xfally/cordova-plugin-ftp#30]
Hi @xfally 
I am trying to simply upload an image from my assets/imgs/ directory.
I know this has been address in #5  and #17 but this doesnt seem to be helping me.

Once I have connected I just use:

```
 this.ftp.upload('assets/imgs/logo.png', '/public_html/logo.jpg')
      .subscribe( (p:any) => {
         console.log(JSON.stringify(p));   
         }, (err:any) => {
             alert(JSON.stringify(err));
         });
```
I am running this from an Ionic 3 web view. I swear I had this working a few weeks ago, able to upload easily and straight away ... am I missing anything obvious?

**Comment by xfally** [comment]
@simonkincaidkintronix As demo in README.md shown, it should be a root path without `file://` prefix. I'm not sure a relative path can work. Can you replace it with root path `/`?

You said it can work a few weeks ago, so what changed?

Furthermore, this project was tested on Nexus 5X Android 6.0.0, and you know it's too old to the newset Android Q. All things (cordova, angular, ionic...) may have changed, so it may work wrong now.
