### ISSUE TITLE
Part of picture

### ISSUE THREAD

**Issue by pc-partner** [xfally/cordova-plugin-ftp#34]
When uploading a picture with code below, sometimes the picture is uploaded for 70-80%. We get a success notification put when looking on the ftp site the picture is missing a part.
Is this a known issue?
```
window.cordova.plugin.ftp.upload(file, xxx + id, function (percent) {
      if (percent == 1) {
        console.info("ftp: upload finish to " + '/www/xxx/' + id);
      } else {
        console.debug("ftp: upload percent=" + percent * 100 + "%");
      }
    }, function (error) {
      console.error("ftp: upload error=" + error);
    });
```

**Comment by xfally** [comment]
Try the latest v1.2.0. If error still exists, reopen this issue.
