### ISSUE TITLE
Uploading text or sqlite db file resulting in zero bytes for IOS

### ISSUE THREAD

**Issue by gv1186** [xfally/cordova-plugin-ftp#35]
Uploading text or sqlite db file resulting in zero bytes for IOS on the server. file size is 8MB
Android working fine for txt and db file.

**Comment by FacundoBistolfi** [comment]
I have the same issue, the console says "Server aborted transfer."

**Comment by xfally** [comment]
I have tried to upload sqlite db which is 10MB, from iOS 14.5 to vsftpd, and work well, please try the latest v1.2.1. If error still exists, reopen this issue.
