### ISSUE TITLE
I am getting error : "Unknown error!"

### ISSUE THREAD

**Issue by nive745** [xfally/cordova-plugin-ftp#4]
Hi,
Please give me solution. I am getting "Unknown error" while uploading file.
We are using
Device: Ipad
IOS : 9.3.2
Framework:Framework7
Cordova version:4.0.1
var FTP = {
            ADDRESS: scope.data.ftp.ADDRESS,
            USERNAME: scope.data.ftp.USERNAME,
            PASSWORD: scope.data.ftp.PASSWORD,
            HOME_PATH: scope.data.ftp.HOME_PATH
        };
        var localFile = scope.data.local.FILE;
        var localFile1 = localFile + '.1';
        var remotePath = scope.data.remote.PATH;
        if (remotePath.substr(-1) != '/') {
            remotePath += '/';
        }
        var remoteFile = remotePath + scope.data.local.FILE.substr(localFile.lastIndexOf('/') + 1);
        //log.debug("xtest: remotePath is " + remotePath);
        //log.debug("xtest: remoteFile is " + remoteFile);
        //log.debug("xtest: localFile is " + localFile);
        //log.debug("xtest: localFile1 is " + localFile1);
        // Tip: Usually init/create window.cordova.plugin.ftp will take some time.
        //      We should listen `deviceready` event for cordova, or `ionicPlatform.ready()` for ionic.
        //      You can find more info in official docs of cordova or ionic.
            if (window.cordova && window.cordova.plugin && window.cordova.plugin.ftp) {
                // 1. connect to one ftp server, then you can do any actions/cmds
                window.cordova.plugin.ftp.connect(FTP.ADDRESS, FTP.USERNAME, FTP.PASSWORD, function() {
                    alert("connect")
                    //log.info("xtest: ftp: connect ok");
                               myApp.showIndicator();
                                //log.info("xtest: ftp: mkdir ok=" + ok);
                                // 4. upload localFile to remote (you can rename at the same time). arg1: localFile, arg2: remoteFile.
                                // - make sure you can ACCESS and READ the localFile.
                                // - (for iOS) if localFile not exists, a blank remoteFile will be created on ftp server.
                                // - if a same named remoteFile exists on ftp server, it will be overrided!

```
                            window.cordova.plugin.ftp.upload(localFile, remoteFile, function(percent) {
                                if (percent == 1) {
                                    //log.info("xtest: ftp: upload finish");
                                    // 4a. cancel download after some time
                                    //timeout(function() {
                                    //window.cordova.plugin.ftp.cancel(function(ok) {
                                    ////log.info("xtest: ftp: cancel ok=" + ok);
                                    //}, function(error) {
                                    ////log.error("xtest: ftp: cancel error=" + error);
                                    //});
                                    //}, 2000);
                                    // 5. download remoteFile to local (you can rename at the same time). arg1: localFile, arg2: remoteFile.
                                    // - make sure you can ACCESS and WRITE the local dir.
                                    // - if one same named localFile exists, it will be overrided!
                                    myApp.hideIndicator()

                                } else {

                                    //log.debug("xtest: ftp: upload percent=" + percent * 100 + "%");
                                }
                            }, function(error) {

                                alert(error)
                                //log.error("xtest: ftp: upload error=" + error);
                            });



            });
        } else {
            //log.error("xtest: ftp: plugin not found!");
        }
```

**Comment by xfally** [comment]
Create a _breakpoint_ at [GRError.m](https://github.com/xfally/cordova-plugin-ftp/blob/master/src/ios/GoldRaccoon/Sources/Utils/GRError.m): `- (NSString *)message` to see the `errorCode`'s value. Refer to [rfc959](http://www.w3.org/Protocols/rfc959/9_References.html): "4.2.1  Reply Codes by Function Groups" for its meaning.

**Comment by nive745** [comment]
This is my error code
Error Domain=com.albertodebortoli.goldraccoon Code=-1000 "(null)" UserInfo={message=Unknown error!}

Thanks for reply

**Comment by xfally** [comment]
Please read my reply carefully. We need the `errorCode` (directly from ftp server) instead of error `message` (parsed from `errorCode`). You can add breakpoint in [GRError.m](https://github.com/xfally/cordova-plugin-ftp/blob/master/src/ios/GoldRaccoon/Sources/Utils/GRError.m):

```
+ (GRErrorCodes)errorCodeWithError:(NSError *)error
{
    // As suggested by RMaddy
    NSDictionary *userInfo = error.userInfo;
    NSNumber *code = [userInfo objectForKey:(id)kCFFTPStatusCodeKey];
```

to see `code`'s value, or

```
- (NSString *)message
{
    NSString *errorMessage;
    switch (self.errorCode) {
```

to see `errorCode`'s value.

Refer to [kCFFTPStatusCodeKey](https://developer.apple.com/reference/cfnetwork/kcfftpstatuscodekey).

**Comment by nive745** [comment]
In this function we below values:
- kCFGetAddrInfoFailureKey = 8
- kCFFTPStatusCodeKey = nil

and geting self.errorCode = 0
- (GRErrorCodes)errorCodeWithError:(NSError *)error
  {
  // As suggested by RMaddy
  NSDictionary *userInfo = error.userInfo; //kCFGetAddrInfoFailureKey = 8
  NSNumber *code = [userInfo objectForKey:(id)kCFFTPStatusCodeKey];  // nil
  
  if (code) {
      return [code intValue];
  }
  
  return 0;
  }

**Comment by xfally** [comment]
`userInfo` just has kCFGetAddrInfoFailureKey instead of kCFFTPStatusCodeKey? Er~ it seems like a DNS resolution failure. Please check your `ftp.ADDRESS` value (if probably, tell me more info about your ftp server). You can also check ftp URL (address), username, password... in [GRStreamInfo.m](https://github.com/xfally/cordova-plugin-ftp/blob/master/src/ios/GoldRaccoon/Sources/Utils/GRStreamInfo.m): `openRead`: `readStreamRef` (I have explained this API in issue #3)

**Comment by nive745** [comment]
Thanks for your quick response.

It does not look like a DNS resolution error, as I am able to connect to the same ftp host from Filezilla and also able to upload the files. I can also connect to the same ftp server, with same credentials from our website and it works from there too. Also, I am able to connect from Cordova app as well, but get an error when I try to upload a file.

Please let me know if you need any other details from me. Meanwhile I will try to check with some other ftp server if I can.

Thank you.

**Comment by xfally** [comment]
Have you tried other actions? e.g. list, download... the same error?

If probably, tell me your test info
- What ftp server used (and local or online ftp server?)
- FTP.ADDRESS string
- FTP.USERNAME and FTP.PASSWORD string

So i can reproduce the error easily.

**Comment by nive745** [comment]
I tried list action, but gives the same error. Below are the details you need: -
1. Its a live ftp server.
2. upload.sportlounge.com
3. user name: 395088-1681  
   password: Isumitele347

**Comment by xfally** [comment]
Have tested with the info you gave on my ionic/angular/cordova App, and all tests passed.

![simulator screen shot 18 aug 2016 11 03 50 am](https://cloud.githubusercontent.com/assets/5096620/17760790/e81daf28-6534-11e6-8d02-d403e28c619a.png)
![simulator screen shot 18 aug 2016 11 06 58 am](https://cloud.githubusercontent.com/assets/5096620/17760798/f1e4c9c4-6534-11e6-8b9e-d4638055e9ea.png)

I noticed that you used Framework7 but didn't listen cordova event `deviceready` to make sure Native layer was ready for work. Suggest you fix it and let us see what will happy.

> You judged `if (window.cordova && window.cordova.plugin && window.cordova.plugin.ftp)`, but that is not enough to say Native is ready.

**Comment by nive745** [comment]
Thanks for your quick support.

I removed all framwork7 code. i am using cordova, jquery library and cordova-plugin-file for get application urls. it's also giving me same error. i am sending you link. You can check my code from this link.

I want to upload ou1qQ.jpg image to server from my code.

And also i uploaded my www folder to ftp credential which i provided you. you can also check if you needed.

http://dev.eoniansoftware.com/sportloungeapp/www/example.html

**Comment by xfally** [comment]
Sorry, i'm busy at work recently, so couldn't reply in time.

Have read your codes. You couldn't access asset file via `cordova.file.applicationDirectory` directly, refer to [cordova-plugin-file PR 84](https://github.com/apache/cordova-plugin-file/pull/84), change it to other accessible path. And you had better not `addEventListener` twice (are you a js newcomer?)

My network is not stable to connect to your test ftp server currently, but have tested on my own ftp server with one new cordova project ([www.zip](https://github.com/xfally/cordova-plugin-ftp/files/433977/www.zip)), and it worked well. You can put it into your cordova project to have a try.

**Comment by xfally** [comment]
Long time no feedback.

**Comment by nive745** [comment]
Thanks so much for your support but this code work for me and i applied this to my project. And sorry, I forgot to closed this topic.

Thanks
