### ISSUE TITLE
open failed: ENOENT to local file in ionic

### ISSUE THREAD

**Issue by estvmachine** [xfally/cordova-plugin-ftp#5]
Hi, when im trying to open a file in the externalDataDirectory and in localPath of my app in Ionic, but always said ENOENT (No such file or directory). 

The route is something like this in the externalDataDirectory: /file:/storage/sdcard0/Android/data/com.ionicframework.granel2379872/files/test.txt.

For local path i try with: '/www/test/test.txt' , '/test/test.txt'

How you make works the upload in Ionic or Cordova?. You have an example for a string 'localFile' that works?.

``` javascript
window.cordova.plugin.ftp.upload(localFile, remoteFile, function(percent) {
....
```

**Comment by xfally** [comment]
Could you print the value of `localFile`? As demo in README.md shown, it should be a root path without `file://` prefix, and you can ACCESS and READ it.

**Comment by estvmachine** [comment]
Well, without the 'file://' works, ThanksWell, without the 'file://' works, Thanks
