### ISSUE TITLE
Cordova InAppBrowser open FTP URL Windows Phone 8

### ISSUE THREAD

**Issue by sumitsoman** [xfally/cordova-plugin-ftp#7]
Could you provide this plugin for WP8? I am developing using Cordova and needed this feature.

[http://stackoverflow.com/questions/42129315/cordova-inappbrowser-open-ftp-url-windows-phone-8](url)

**Comment by xfally** [comment]
Sorry, no plan for windows phone now, but maybe you can implement it by yourself.

Docs: https://msdn.microsoft.com/en-us/magazine/dn385710.aspx
Codes: http://download.microsoft.com/download/7/C/9/7C994C6D-5ADA-4FC2-AC9C-F0DD492FFA0B/Code_Gupta.WPFTP.0913-Final.zip

You can fork cordova-plugin-ftp and add windows phone support based on it. After good test, you can even make a PR to contribute your codes. Good luck~
