### ISSUE TITLE
java.net.SocketTimeoutException on android

### ISSUE THREAD

**Issue by subhash8108** [xfally/cordova-plugin-ftp#8]
Hello,

I have used your plugin on cordova android,

Cordova version : 6.5.0
![android-platform](https://cloud.githubusercontent.com/assets/542535/23214256/fe35ca5a-f933-11e6-8b98-cedee5776652.png)

FTP connected successfully and upload start very smoothly, but every time 99% upload file after get error message show.

you can see screen shot. (99% upload successfully)

![ftp_upload](https://cloud.githubusercontent.com/assets/542535/23213864/a7fbb7cc-f932-11e6-9ae2-76d6b5f51f50.png)

you can see screen shot. (Error message)

![ftp_upload_error](https://cloud.githubusercontent.com/assets/542535/23213952/fdf90a26-f932-11e6-964a-f574324ae803.png)

I was try 9mb upload as well as 4mb upload, but same problem 99% upload after showing error message.

Please help me.

**Comment by xfally** [comment]
Please confirm
1. First `java.net.SocketTimeoutException`, then `99%`?
2. How much time did you wait to see the error from normal upload process?
3. Did your test your ftp server via other ftp client?
4. Try my [test codes](https://github.com/xfally/cordova-plugin-ftp/files/433977/www.zip) in your project, and see what happy?

Additionally, I created and tested the plugin on just Cordova version 4.x, and have no chance to test the newer versions. I'm not sure it has some relation or not.

**Comment by subhash8108** [comment]
Hello,

1. I have try 5 times and every time 99% after error get.
2. every time
3. yes, normally working ftp with your plugin, and perfect working.

Please help me for this issue.

Thanks
Subhash

**Comment by xfally** [comment]
2. I means how long?
3. My plugin? I means try other ftp client to test your ftp server.
4. Have tested with my [www.zip](https://github.com/xfally/cordova-plugin-ftp/files/433977/www.zip)?

**Comment by subhash8108** [comment]
Hi,

I was tried 5 time and every time 99% after get error. and ios perfect working

why  99% after get error of java.

Thanks
Subhash

**Comment by xfally** [comment]
I can't reproduce the error. Could you please afford
1. The codes which can reproduce the error. As simple as possible.
2. The Android device name and version. Have you tested other devices?
3. The ftp server name and version.

**Comment by xfally** [comment]
Long time no feedback.

**Comment by coderalexis** [comment]
I have the same error, any solution?
